metadata:
  name: exp2
  date: 06/03/2025

model: 
  name: ConvLSTM_Autoencoder
  description: A Convolutional LSTM architecture that classifies timeseries into categorical classes.
  url: s3://manolo-data/models/conv_lstm_ae.pth

  parameters: 
    id: conv_lstm_ae
    num_feats: 2
    latent_seq_len: 1 
    latent_num_feats: 8 
    hidden_size: 4
    num_layers: 1
    dropout: 0.05

inference:
  parameters:
    batch_size: 512
    seq_len: 240
    epochs: 1000
    loss: CrossEntropyLoss

  dataset: s3://manolo-data/datasets/bitbrain-ds/
  
metrics:
  - accuracy
  - f1_score
  - precision
  - recall