[tool.poetry]
name = "kobe2"
version = "0.26"
packages = [
    { include = "kobe2" }
]
description = "Kobe2: Benchmarking for Machine Learning"
authors = [ "Natalia Koliou <nataliakoliou@iit.demokritos.gr>",
	    "Stasinos Konstantopoulos <konstant@iit.demokritos.gr>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"        
pandas = "^2.1"
numpy = "^1.26"    

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"